# Generated by Django 5.2.7 on 2026-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0002_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pos 1 (Esq)'), (2, 'Pos 2 (Esq)'), (3, 'Pos 3 (Esq)'), (4, 'Pos 4 (Esq)'), (5, 'Pos 5 (Dir)'), (6, 'Pos 6 (Dir)'), (7, 'Pos 7 (Dir)'), (8, 'Pos 8 (Dir)')], default=1),
        ),
    ]
